# Generated by Django 3.1.2 on 2020-10-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_api.companyaddress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanentAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_api.permanentaddress'),
        ),
    ]
