# Generated by Django 3.1.2 on 2020-10-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_auto_20201008_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companyAddress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permanentAddress',
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
        migrations.DeleteModel(
            name='PermanentAddress',
        ),
    ]
